export a
export b=
export c=""
export d="   "
export e="ceciestuntest"
export f="   ceci    est   un    test   "
export g='"'
export h='""'
export j='  "  '
export k='  "  "  '
export l='  ceci   "est"   un ""   test'
export m='"ceci    est   un   test"'
export n="'"
export o="''"
export p="  '  "
export q="  '  '  "
export r="  ceci   'est'   un ''   test"
export s="'ceci    est   un   test'"
export t="\\"
export u="  \\  "
export v="  \\  \\  "
export w="\\\\\\ceci\\est\\un\\test\\\\\\"
export x="  ceci   \\\\est\\\\   un \\\\   test"
export y="|"
export z="  <  "
export ab="  <  |  "
export ac="<>|ceci||est>>un<<test>>|"
export ad="SG< DS>G|DS G \'L}L    \"S}|<<DF\"}|\'\">>DS    }|F\"D<S |G|\'\':DS     G:DS\"\" GDS\"G DS}|   | DGS> GDS<L "
export echo="echo"
export cmd="$echo $ac | grep test $r"