echo $a | cat -e > out
echo $b | cat -e >> out
echo $c | cat -e >> out
echo $d | cat -e >> out
echo $e | cat -e >> out
echo $f | cat -e >> out
echo $g | cat -e >> out
echo $h | cat -e >> out
echo $j | cat -e >> out
echo $k | cat -e >> out
echo $l | cat -e >> out
echo $m | cat -e >> out
echo $n | cat -e >> out
echo $o | cat -e >> out
echo $p | cat -e >> out
echo $q | cat -e >> out
echo $r | cat -e >> out
echo $s | cat -e >> out
echo $t | cat -e >> out
echo $u | cat -e >> out
echo $v | cat -e >> out
echo $w | cat -e >> out
echo $x | cat -e >> out
echo $y | cat -e >> out
echo $z | cat -e >> out
echo $ab | cat -e >> out
echo $ac | cat -e >> out
echo $ad | cat -e >> out
echo $echo | cat -e >> out
echo "$cmd" | cat -e >> out
$cmd >> out
 >> out
echo "$a" | cat -e >> out
echo "$b" | cat -e >> out
echo "$c" | cat -e >> out
echo "$d" | cat -e >> out
echo "$e" | cat -e >> out
echo "$f" | cat -e >> out
echo "$g" | cat -e >> out
echo "$h" | cat -e >> out
echo "$j" | cat -e >> out
echo "$k" | cat -e >> out
echo "$l" | cat -e >> out
echo "$m" | cat -e >> out
echo "$n" | cat -e >> out
echo "$o" | cat -e >> out
echo "$p" | cat -e >> out
echo "$q" | cat -e >> out
echo "$r" | cat -e >> out
echo "$s" | cat -e >> out
echo "$t" | cat -e >> out
echo "$u" | cat -e >> out
echo "$v" | cat -e >> out
echo "$w" | cat -e >> out
echo "$x" | cat -e >> out
echo "$y" | cat -e >> out
echo "$z" | cat -e >> out
echo "$ab" | cat -e >> out
echo "$ac" | cat -e >> out
echo "$ad" | cat -e >> out
echo $echo | cat -e >> out
echo "$cmd" | cat -e >> out
$cmd >> out